import { useState, type CSSProperties } from "react";
import { Link, useParams } from "react-router-dom";
import { businesses, products, services, type Product, type Service } from "../data/mockData";
import { getLikeCount, getLikeIds, toggleLike } from "../services/userDataService";
import { PageLayout } from "../components/PageLayout";
import { ThumbsDownIcon, ThumbsUpIcon } from "../components/ActionIcons";
import { useAccountGate } from "../hooks/useAccountGate";
import "./OfferDetail.css";
import "./OfferDetailEnhancements.css";
export function ProductDetail() { return <OfferDetail kind="product"/>; }
export function ServiceDetail() { return <OfferDetail kind="service"/>; }
function OfferDetail({ kind }: { kind: "product" | "service" }) {
 const { id = "" } = useParams(); const [likes, setLikes] = useState(getLikeIds); const requireAccount = useAccountGate();
 const offer = kind === "product" ? products.find((item) => item.id === id) : services.find((item) => item.id === id); const business = businesses.find((item) => item.id === offer?.businessId); const isProduct = kind === "product";
 if (!offer || !business) return <PageLayout><div className="business-not-found"><h1>No encontramos {isProduct ? "este producto" : "este servicio"}</h1><Link to="/home">Volver a explorar</Link></div></PageLayout>;
 const item = offer as Product | Service; const price = isProduct ? (item as Product).price ? new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format((item as Product).price!) : "Consulta disponibilidad" : (item as Service).priceLabel ?? "Consulta disponibilidad";
 return <PageLayout className="offer-detail-page"><Link className="offer-detail-back" to={`/business/${business.id}`}>← Volver a {business.name}</Link><section className="offer-detail"><div className="offer-detail-image"><img src={item.image} alt={item.name}/><span>{isProduct ? "Producto" : "Servicio"}</span></div><div className="offer-detail-copy"><span className="offer-detail-label">{business.category}</span><h1>{item.name}</h1><p>{item.description}</p><strong className="offer-detail-price">{price}</strong><Link className="offer-business-card" to={`/business/${business.id}`}><img src={business.image} alt=""/><span><small>EN ESTE ESTABLECIMIENTO</small><b>{business.name}</b><em>{business.address}</em></span><i>→</i></Link><div className="offer-business-rating" aria-label={`Calificación ${business.rating} de 5`}><span className="offer-business-stars" style={{ "--rating": business.rating * 20 } as CSSProperties}>★★★★★</span><b>{business.rating.toFixed(1)}</b><small>({business.reviewCount} opiniones)</small></div><div className="offer-detail-actions"><Link to={`/business/${business.id}`} className="offer-detail-primary">Consultar en el negocio →</Link><button type="button" title={likes.includes(item.id) ? "Quitar me gusta" : "Me gusta"} aria-pressed={likes.includes(item.id)} className={`entity-action entity-like entity-product-like${likes.includes(item.id) ? " is-active" : ""}`} aria-label={likes.includes(item.id) ? `Quitar me gusta a ${item.name}` : `Me gusta ${item.name}`} onClick={() => requireAccount(() => setLikes(toggleLike(item.id)))}>{likes.includes(item.id) ? <ThumbsDownIcon/> : <ThumbsUpIcon/>}</button><span className={`offer-like-count${likes.includes(item.id) ? " is-active" : ""}`}>{likes.includes(item.id) ? "Ya no me gusta" : "Me gusta"}</span></div><small className="offer-like-count-note">A {getLikeCount(item.id, item.likeCount ?? 0)} personas les gusta este {isProduct ? "producto" : "servicio"}.</small><Link className="offer-detail-report" to={`/report?type=${kind}&id=${item.id}`}>Reportar información de {isProduct ? "este producto" : "este servicio"}</Link></div></section></PageLayout>;
}
