import { useState, type FormEvent } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { Logo } from "@wit/ui";
import { startPreviewUserSession } from "../services/userDataService";
import "./Register.css";
import "./RegisterEnhancements.css";
import "./RegisterAlert.css";

function safeReturn(value: string | null) { return value?.startsWith("/") && !value.startsWith("//") && !value.startsWith("/register") ? value : "/profile"; }
function GoogleIcon() { return <svg aria-hidden="true" viewBox="0 0 48 48"><path fill="#4285F4" d="M43.6 24.5c0-1.4-.1-2.8-.4-4.1H24v7.8h11a9.5 9.5 0 0 1-4.1 6.2v5.1h6.6c3.9-3.6 6.1-8.9 6.1-15Z"/><path fill="#34A853" d="M24 44c5.5 0 10.1-1.8 13.5-4.8l-6.6-5.1c-1.8 1.2-4.1 2-6.9 2-5.3 0-9.8-3.6-11.4-8.4H5.8V33A20 20 0 0 0 24 44Z"/><path fill="#FBBC05" d="M12.6 27.7a12 12 0 0 1 0-7.4v-5.1H5.8a20 20 0 0 0 0 17.6l6.8-5.1Z"/><path fill="#EA4335" d="M24 12c3 0 5.6 1 7.7 3l5.8-5.8A19.4 19.4 0 0 0 24 4 20 20 0 0 0 5.8 15.2l6.8 5.1C14.2 15.6 18.7 12 24 12Z"/></svg>; }
function FacebookIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24"><path fill="#1877F2" d="M24 12a12 12 0 1 0-13.9 11.9v-8.4H7.1V12h3V9.3c0-3 1.8-4.7 4.5-4.7 1.3 0 2.6.2 2.6.2v2.9h-1.5c-1.5 0-2 .9-2 1.9V12h3.3l-.5 3.5h-2.8v8.4A12 12 0 0 0 24 12Z"/><path fill="#fff" d="M16.6 15.5 17.1 12h-3.3V9.6c0-1 .5-1.9 2-1.9h1.5V4.8s-1.3-.2-2.6-.2c-2.7 0-4.5 1.7-4.5 4.7V12h-3v3.5h3v8.4a12.2 12.2 0 0 0 3.6 0v-8.4h2.8Z"/></svg>; }
const providers = [{ name: "Google", Icon: GoogleIcon }, { name: "Facebook", Icon: FacebookIcon }];
export default function Register() { const navigate = useNavigate(); const [params] = useSearchParams(); const [mode, setMode] = useState<"register"|"login">("register"); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [message, setMessage] = useState(""); const [accepted, setAccepted] = useState(false); const returnTo = safeReturn(params.get("next"));
 function submit(event: FormEvent) { event.preventDefault(); if (mode === "register" && !accepted) { setMessage("Acepta los términos y la política de privacidad para continuar."); return; } if (mode === "register" && password !== confirmPassword) { setMessage("Las contraseñas no coinciden."); return; } setMessage("El formulario está listo. Conectaremos el servicio de cuentas en la siguiente etapa."); }
 return <main className="register-page"><header className="register-header"><Link to="/home" aria-label="WIT, inicio"><Logo/></Link><Link to="/home">Seguir explorando</Link></header><section className="register-panel"><span className="register-eyebrow">TU ESPACIO EN WIT</span><h1>{mode === "register" ? "Crea tu cuenta" : "Inicia sesión"}</h1><p>Guarda tiendas, marca productos y servicios, y comparte tu opinión.</p><div className="register-social-options">{providers.map(({ name, Icon }) => <button key={name} type="button" className="register-provider-button" onClick={() => setMessage(`El acceso con ${name} estará disponible cuando conectemos la autenticación.`)}><Icon/><span>Continuar con {name}</span></button>)}</div><div className="register-divider"><span>o con tu correo</span></div><form onSubmit={submit}>{mode === "register" && <label>¿Cómo te llamas?<input autoComplete="name" required maxLength={60} placeholder="Tu nombre"/></label>}<label>Correo electrónico<input type="email" autoComplete="email" required placeholder="tu@correo.com"/></label><label>Contraseña<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={mode === "register" ? "new-password" : "current-password"} minLength={8} required placeholder="Al menos 8 caracteres"/></label>{mode === "register" && <label>Confirmar contraseña<input type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} autoComplete="new-password" minLength={8} required placeholder="Repite tu contraseña"/></label>}{mode === "register" && <label className="register-legal-check"><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)}/><span>Acepto los <Link to="/legal/terms">Términos y condiciones</Link> y la <Link to="/legal/privacy">Política de privacidad</Link>.</span></label>}<button className="register-submit" type="submit">{mode === "register" ? "Crear cuenta" : "Iniciar sesión"}</button></form>{mode === "login" && <Link className="register-mode-switch" to="/recover-password">¿Olvidaste tu contraseña?</Link>}{message && <p className="register-status" role="status">{message}</p>}<button className="register-mode-switch" type="button" onClick={() => { setMode(mode === "register" ? "login" : "register"); setMessage(""); }}>{mode === "register" ? "¿Ya tienes una cuenta? Inicia sesión" : "¿Aún no tienes cuenta? Regístrate"}</button><button className="register-preview-button" type="button" onClick={() => { startPreviewUserSession(); navigate(returnTo, { replace: true }); }}>Entrar en vista previa como usuario registrado</button><small className="register-disclaimer">El registro y los accesos sociales son una maqueta visual por ahora. Tus datos no se envían ni se guardan.</small></section></main>; }
