import { useMemo, useState, type FormEvent } from "react";
import { Link, useLocation, useSearchParams } from "react-router-dom";
import { businesses, reviews as sampleReviews } from "../data/mockData";
import { deleteUserRating, deleteUserReview, getUserRatings, getUserReviews, saveUserRating, saveUserReview } from "../services/userDataService";
import { useAuth } from "../context/AuthContext";
import { PageLayout } from "../components/PageLayout";
import "./Reviews.css";
import "./ReviewsEnhancements.css";

export default function Reviews() {
 const [params] = useSearchParams(); const location = useLocation(); const { isAuthenticated } = useAuth(); const businessId = params.get("businessId") ?? ""; const view = params.get("view"); const business = businesses.find((item) => item.id === businessId); const [rating, setRating] = useState(0); const [comment, setComment] = useState(""); const [revision, setRevision] = useState(0); const [submitted, setSubmitted] = useState(false); const [deleted, setDeleted] = useState(false); const [pendingDelete, setPendingDelete] = useState<string | null>(null); const canReview = isAuthenticated;
 const mine = useMemo(() => getUserReviews().sort((a,b) => Date.parse(b.date) - Date.parse(a.date)), [revision]); const ratings = useMemo(() => getUserRatings().sort((a,b) => Date.parse(b.createdAt) - Date.parse(a.createdAt)), [revision]); const shown = business ? [...sampleReviews.filter((item) => item.businessId === businessId), ...mine.filter((item) => item.businessId === businessId)] : view === "opinions" ? mine : [];
 function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!business || !rating || !comment.trim()) return; saveUserRating(business.id, rating); saveUserReview({ id: `review-${Date.now()}`, businessId: business.id, author: "Tú", rating, date: new Date().toISOString(), comment: comment.trim() }); setComment(""); setRating(0); setSubmitted(true); setRevision((value) => value + 1); }
 if (!business) return <PageLayout className="reviews-page"><Link className="offer-detail-back" to="/profile">← Volver al perfil</Link><div className="user-page-heading"><h1>Mis opiniones</h1>{deleted && <p className="review-success" role="status">La opinión se eliminó correctamente.</p>}</div>{view !== "ratings" && <section className="reviews-list">{mine.length ? mine.map((review) => <article className="review-row" key={review.id}><span className="review-avatar">T</span><div><b>{businesses.find((item) => item.id === review.businessId)?.name ?? "Negocio"}</b><span className="review-stars">{"★".repeat(review.rating)}</span><p>{review.comment}</p><button className="review-delete-button" type="button" onClick={() => setPendingDelete(review.id)}>Eliminar opinión</button>{pendingDelete === review.id && <span className="review-delete-confirm">¿Eliminarla? <button type="button" onClick={() => { deleteUserReview(review.id); setPendingDelete(null); setDeleted(true); setRevision((value) => value + 1); }}>Sí</button><button type="button" onClick={() => setPendingDelete(null)}>No</button></span>}</div></article>) : <div className="user-empty-state"><h2>Aún no has escrito opiniones</h2><p>Cuando compartas una experiencia, aparecerá aquí.</p></div>}</section>}{view === "ratings" && <section className="reviews-list"><h2>Calificaciones</h2>{ratings.length ? ratings.map((item) => <article className="review-row" key={item.id}><span className="review-avatar">★</span><div><b>{businesses.find((businessItem) => businessItem.id === item.businessId)?.name ?? "Negocio"}</b><span className="review-stars">{"★".repeat(item.rating)}{"☆".repeat(5-item.rating)}</span><time>{new Date(item.createdAt).toLocaleDateString("es-CO")}</time><button className="review-delete-button" type="button" onClick={() => { deleteUserRating(item.id); setRevision((value) => value + 1); }}>Eliminar calificación</button></div></article>) : <div className="user-empty-state"><h2>Aún no has calificado lugares</h2><p>Podrás hacerlo desde la ficha de un negocio.</p></div>}</section>}</PageLayout>;
 return <PageLayout className="reviews-page"><Link className="offer-detail-back" to={`/business/${business.id}`}>← Volver a {business.name}</Link><div className="user-page-heading"><span>EXPERIENCIAS LOCALES</span><h1>Opiniones sobre {business.name}</h1><p>Las estrellas y la opinión se envían juntas para mantener valoraciones confiables.</p></div>{canReview ? <form className="review-form" onSubmit={submit}><b>¿Cómo fue tu experiencia?</b><small className="review-form-hint">Selecciona las estrellas y escribe tu opinión para compartir una nueva experiencia.</small><div className="review-rating-pick" role="group" aria-label="Califica de una a cinco estrellas">{[1,2,3,4,5].map((value) => <button key={value} type="button" aria-label={`${value} estrellas`} aria-pressed={rating === value} className={value <= rating ? "selected" : ""} onClick={() => { setRating(value); setSubmitted(false); }}>★</button>)}</div><label className="sr-only" htmlFor="review-comment">Escribe tu opinión</label><textarea id="review-comment" value={comment} onChange={(event) => { setComment(event.target.value); setSubmitted(false); }} placeholder="Escribe tu opinión (obligatorio)" rows={3} maxLength={500}/><button type="submit" disabled={!rating || !comment.trim()}>Enviar calificación y opinión</button>{submitted && <p className="review-success" role="status">¡Gracias por calificar! Tu aporte ya fue enviado.</p>}</form> : <div className="review-login-required"><p>Para calificar u opinar, primero crea tu cuenta o entra a WIT.</p><Link to={`/register?next=${encodeURIComponent(`${location.pathname}${location.search}`)}`}>Crear cuenta o entrar →</Link></div>}<section className="reviews-list"><h2>Opiniones <span>{shown.length}</span></h2>{shown.length ? shown.map((review) => <article className="review-row" key={review.id}><span className="review-avatar">{review.author.charAt(0)}</span><div><div className="review-row-heading"><b>{review.author}</b><time>{new Date(review.date).toLocaleDateString("es-CO")}</time></div><span className="review-stars">{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span>{review.comment && <p>{review.comment}</p>}</div></article>) : <div className="user-empty-state"><h2>Aún no hay opiniones</h2><p>Cuando las personas compartan su experiencia, podrás leerla aquí.</p></div>}</section></PageLayout>;
}
