import { useEffect, useRef, useState } from "react";
import type { Business } from "../data/mockData";
import { getBusinessCoordinates } from "../utils/coordinates";
import "./GoogleDynamicMap.css";
declare global { interface Window { google?: any; __witGoogleMapsPromise?: Promise<void>; } }
function loadMaps(key: string): Promise<void> { if (window.google?.maps) return Promise.resolve(); if (window.__witGoogleMapsPromise) return window.__witGoogleMapsPromise; window.__witGoogleMapsPromise = new Promise((resolve, reject) => { const script = document.createElement("script"); script.src = `https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&v=weekly`; script.async = true; script.onload = () => resolve(); script.onerror = () => reject(new Error("No se pudo cargar Google Maps")); document.head.appendChild(script); }); return window.__witGoogleMapsPromise; }
export function GoogleDynamicMap({ businesses, query }: { businesses: Business[]; query?: string }) { const hostRef = useRef<HTMLDivElement>(null); const mapRef = useRef<any>(null); const markersRef = useRef<any[]>([]); const [status, setStatus] = useState<"loading"|"ready"|"error"|"missing">("loading"); const key = import.meta.env.VITE_GOOGLE_MAPS_API_KEY?.trim();
 useEffect(() => { if (!key) { setStatus("missing"); return; } let active = true; void loadMaps(key).then(() => { if (!active || !hostRef.current || mapRef.current) return; mapRef.current = new window.google.maps.Map(hostRef.current, { center: { lat: 3.5394, lng: -76.3036 }, zoom: 14, mapTypeControl: false, streetViewControl: false, fullscreenControl: true }); if (navigator.geolocation) navigator.geolocation.getCurrentPosition(({ coords }) => mapRef.current?.setCenter({ lat: coords.latitude, lng: coords.longitude }), () => undefined, { enableHighAccuracy: false, timeout: 5000, maximumAge: 300000 }); setStatus("ready"); }).catch(() => { if (active) setStatus("error"); }); return () => { active = false; }; }, [key]);
 useEffect(() => { const map = mapRef.current; if (!map || !window.google?.maps) return; markersRef.current.forEach((marker) => marker.setMap(null)); const bounds = new window.google.maps.LatLngBounds(); markersRef.current = businesses.map((business) => { const position = getBusinessCoordinates(business); bounds.extend(position); return new window.google.maps.Marker({ map, position, title: business.name }); }); if (businesses.length === 1) { map.setCenter(getBusinessCoordinates(businesses[0])); map.setZoom(15); } else if (businesses.length > 1) map.fitBounds(bounds, 54); }, [businesses, query]);
 if (status === "missing") return <div className="dynamic-map-fallback"><b>El mapa se activará al configurar Google Maps.</b><p>Mientras tanto puedes explorar los resultados en lista.</p></div>; if (status === "error") return <div className="dynamic-map-fallback"><b>No pudimos cargar el mapa en este momento.</b><p>Revisa tu conexión e inténtalo nuevamente.</p></div>; return <div className="dynamic-map"><div ref={hostRef} className="dynamic-map__canvas" aria-label="Mapa de resultados" />{status === "loading" && <div className="dynamic-map__loading">Cargando mapa…</div>}</div>; }
