import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Panel, StatePanel } from '../components/common';
import { Icon } from '../components/Icon';
import { BusinessBadge } from '../components/businesses/BusinessBadge';
import { businessStatusLabels, claimLabels, daysRemaining, listBusinesses, visibilityLabels } from '../services/businessService';
import { businessInitials, filterBusinesses, plainDate } from '../utils/business';
import type { ManagedBusiness } from '../types/business';

const pageSize = 8;
export function BusinessesPage() {
  const [params, setParams] = useSearchParams(); const [data, setData] = useState<ManagedBusiness[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [attempt, setAttempt] = useState(0);
  useEffect(() => { let active = true; setLoading(true); setError(false); listBusinesses().then(items => { if (active) setData(items); }).catch(() => { if (active) setError(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [attempt]);
  function filter(key: string, value: string) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); next.delete('page'); if (key === 'country') next.delete('city'); setParams(next, { replace: true }); }
  const filtered = filterBusinesses(data, params); const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const page = Math.min(totalPages, Math.max(1, Math.floor(Number(params.get('page'))) || 1)); const rows = filtered.slice((page - 1) * pageSize, page * pageSize);
  const options = (key: 'category' | 'country' | 'city') => [...new Set(data.filter(item => key !== 'city' || !params.get('country') || item.location.country === params.get('country')).map(item => key === 'category' ? item.category : item.location[key]))].sort();
  const activeFilters = ['q', 'status', 'visibility', 'claim', 'category', 'country', 'city'].filter(key => params.get(key));
  const stats = [{ label: 'Negocios en esta muestra', value: data.length, icon: 'store' }, { label: 'Por verificar', value: data.filter(item => ['pending', 'information'].includes(item.verification.status)).length, icon: 'shield', status: 'pending' }, { label: 'Próximos a vencer', value: data.filter(item => item.visibility.status === 'visible' && (daysRemaining(item.visibility.expiresAt) ?? 0) > 0 && (daysRemaining(item.visibility.expiresAt) ?? 8) <= 7).length, icon: 'clock', visibility: 'expiring' }, { label: 'En recuperación', value: data.filter(item => item.status === 'recovery').length, icon: 'box', status: 'recovery' }];
  return <><div className="page-heading"><div><p className="eyebrow">SUPERVISIÓN DE ESTABLECIMIENTOS</p><h1>Negocios<span className="heading-dot">.</span></h1><p>Conoce cada negocio. Verifica su información y acompaña su presencia en WIT.</p></div><span className="mock-indicator"><span className="live-dot" /> Datos de demostración</span></div>
    {loading ? <StatePanel kind="loading" title="Cargando negocios…" message="Preparamos los establecimientos y su información administrativa." /> : error ? <StatePanel kind="error" title="No pudimos cargar los negocios" message="Intenta nuevamente para consultar la información." retry={() => setAttempt(attempt + 1)} /> : <>
    <section className="business-stats" aria-label="Resumen de negocios">{stats.map(stat => <button className={`business-stat ${stat.status && params.get('status') === stat.status || stat.visibility && params.get('visibility') === stat.visibility ? 'is-selected' : ''}`} key={stat.label} onClick={() => { const next = new URLSearchParams(); if (stat.status) next.set('status', stat.status); if (stat.visibility) next.set('visibility', stat.visibility); setParams(next); }}><div><span>{stat.label}</span><strong>{stat.value}</strong></div><span className="metric-icon"><Icon name={stat.icon} /></span></button>)}</section>
    <section className="panel business-directory"><div className="directory-heading"><div><h2>Directorio de negocios</h2><p>{filtered.length} {filtered.length === 1 ? 'establecimiento' : 'establecimientos'}</p></div><label className="sort-label">Ordenar por<select value={params.get('sort') || 'updated'} onChange={event => filter('sort', event.target.value)}><option value="updated">Última actualización</option><option value="created">Registro más reciente</option><option value="name">Nombre A – Z</option><option value="expiry">Próximo vencimiento</option></select></label></div>
    <div className="directory-toolbar"><div className="directory-search"><Icon name="search" size={18} /><input aria-label="Buscar negocio, propietario o teléfono" placeholder="Buscar negocio, propietario o teléfono…" value={params.get('q') || ''} onChange={event => filter('q', event.target.value)} /></div><label>Estado<select value={params.get('status') || ''} onChange={event => filter('status', event.target.value)}><option value="">Todos los estados</option>{Object.entries(businessStatusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Visibilidad<select value={params.get('visibility') || ''} onChange={event => filter('visibility', event.target.value)}><option value="">Toda la visibilidad</option><option value="expiring">Próximos a vencer</option>{Object.entries(visibilityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    <div className="directory-filters"><label>Categoría<select value={params.get('category') || ''} onChange={event => filter('category', event.target.value)}><option value="">Todas las categorías</option>{options('category').map(value => <option key={value}>{value}</option>)}</select></label><label>País<select value={params.get('country') || ''} onChange={event => filter('country', event.target.value)}><option value="">Todos los países</option>{options('country').map(value => <option key={value}>{value}</option>)}</select></label><label>Ciudad<select value={params.get('city') || ''} onChange={event => filter('city', event.target.value)}><option value="">Todas las ciudades</option>{options('city').map(value => <option key={value}>{value}</option>)}</select></label><label>Reclamación<select value={params.get('claim') || ''} onChange={event => filter('claim', event.target.value)}><option value="">Todas las reclamaciones</option>{Object.entries(claimLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{activeFilters.length > 0 && <button className="text-button clear-filters" onClick={() => setParams({})}><Icon name="close" size={14} /> Limpiar filtros ({activeFilters.length})</button>}</div>
    {!rows.length ? <StatePanel kind="empty" title="No hay negocios con estos filtros" message="Prueba otro nombre o elimina algún filtro para ampliar la búsqueda." retry={() => setParams({})} /> : <>
    <div className="business-table-wrap"><table className="business-table"><caption className="sr-only">Directorio de establecimientos de WIT</caption><thead><tr><th>Negocio / propietario</th><th>Ubicación</th><th>Estado</th><th>Visibilidad / vigencia</th><th>Perfil</th><th><span className="sr-only">Abrir detalle</span></th></tr></thead><tbody>{rows.map(item => <tr key={item.id}><td><Link to={`${item.id}?${params.toString()}`} className="business-cell"><span className="business-avatar">{businessInitials(item.name)}</span><div><strong>{item.name}</strong><small>{item.category}</small><span>{item.owner?.name || item.claimant?.name || 'Sin propietario'}</span></div></Link></td><td><strong>{item.location.city}</strong><small>{item.location.region}</small><small>{item.location.country}</small></td><td><BusinessBadge status={item.status} label={businessStatusLabels[item.status]} /><small>{claimLabels[item.claimStatus]}</small></td><td><BusinessBadge status={item.visibility.status} label={visibilityLabels[item.visibility.status]} /><small>{plainDate(item.visibility.expiresAt)}</small>{item.visibility.expiresAt && <span className={`expiry-note ${(daysRemaining(item.visibility.expiresAt) ?? 0) <= 7 ? 'soon' : ''}`}>{(daysRemaining(item.visibility.expiresAt) ?? 0) > 0 ? `${daysRemaining(item.visibility.expiresAt)} días restantes` : 'Vigencia vencida'}</span>}</td><td><strong>{item.completeness} %</strong><div className="profile-progress"><span style={{ width: `${item.completeness}%` }} /></div><small>{item.content.filter(content => content.kind === 'product').length} productos · {item.content.filter(content => content.kind === 'service').length} servicios</small></td><td><Link className="icon-button" to={`${item.id}?${params.toString()}`} aria-label={`Ver ${item.name}`}><Icon name="arrow" size={18} /></Link></td></tr>)}</tbody></table></div>
    <div className="business-mobile-list">{rows.map(item => <Link to={`${item.id}?${params.toString()}`} className="business-mobile-card" key={item.id}><div className="mobile-business-heading"><span className="business-avatar">{businessInitials(item.name)}</span><div><strong>{item.name}</strong><small>{item.category} · {item.location.city}</small></div><Icon name="arrow" size={17} /></div><div className="mobile-business-badges"><BusinessBadge status={item.status} label={businessStatusLabels[item.status]} /><BusinessBadge status={item.visibility.status} label={visibilityLabels[item.visibility.status]} /></div><div className="mobile-business-meta"><span>{item.owner?.name || item.claimant?.name || 'Sin propietario'}</span><strong>Perfil {item.completeness} %</strong></div><small className="mobile-expiry">Vencimiento: {plainDate(item.visibility.expiresAt)}</small></Link>)}</div>
    <div className="business-pagination"><span>Mostrando {(page - 1) * pageSize + 1}–{Math.min(page * pageSize, filtered.length)} de {filtered.length}</span><div><button className="secondary-button" disabled={page <= 1} onClick={() => { const next = new URLSearchParams(params); next.set('page', String(page - 1)); setParams(next); }}>Anterior</button><span>Página {page} de {totalPages}</span><button className="secondary-button" disabled={page >= totalPages} onClick={() => { const next = new URLSearchParams(params); next.set('page', String(page + 1)); setParams(next); }}>Siguiente</button></div></div></>}
    </section><Panel title="Una revisión, con contexto" subtitle="Verificación, vigencia y moderación son procesos independientes." className="business-guidance"><div><Icon name="shield" /><p>Una reclamación normal no exige documentación. Las discrepancias se escalan para revisión. Abrir un negocio te permite consultar toda su información y el historial de decisiones.</p></div></Panel></>}
  </>;
}
