import { useState, type FormEvent } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { Logo } from '@wit/ui';
import { getSession, login } from '../services/adminService';
import { Icon } from '../components/Icon';
export function LoginPage() { const navigate = useNavigate(); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
if (getSession()) return <Navigate to="/dashboard" replace />;
async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { await login(String(form.get('email')), String(form.get('password')), form.get('remember') === 'on'); navigate('/dashboard', { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No pudimos iniciar la sesión. Intenta nuevamente.'); } finally { setBusy(false); } } async function demoLogin() { setBusy(true); setError(''); try { await login('danilo.jaramillo@hotmail.com', 'demo-access', true); navigate('/dashboard', { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No pudimos iniciar la sesión. Intenta nuevamente.'); } finally { setBusy(false); } }
return <main className="login-page"><section className="login-story"><div className="brand"><Logo /><span>ADMIN</span></div><div><span className="login-kicker">WHERE IS THAT?</span><h1>Todo WIT.<br />Una visión clara.</h1><p>Supervisa el ecosistema, acompaña su crecimiento y presta atención a lo que realmente importa.</p><div className="login-pill"><Icon name="shield" /> Centro de control administrativo</div></div><small>Descubrimiento local. Conexiones reales.</small></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><span className="state-icon"><Icon name="lock" size={26} /></span><p className="eyebrow">WIT ADMIN</p><h2>Bienvenido al centro de control</h2><p>Inicia sesión para administrar el ecosistema WIT.</p><label htmlFor="email">Correo electrónico</label><input id="email" name="email" type="email" autoComplete="username" defaultValue="danilo.jaramillo@hotmail.com" placeholder="admin@example.test" required /><label htmlFor="password">Contraseña</label><div className="password-field"><input id="password" name="password" type={show ? 'text' : 'password'} autoComplete="current-password" defaultValue="demo-access" minLength={4} required placeholder="Al menos 4 caracteres" /><button type="button" aria-label={show ? 'Ocultar contraseña' : 'Mostrar contraseña'} aria-pressed={show} onClick={() => setShow(!show)}><Icon name="eye" /></button></div><div className="login-options"><label><input type="checkbox" name="remember" defaultChecked /> Recordar sesión</label><button type="button" className="text-button" onClick={() => navigate('/recover-password')}>Recuperar contraseña</button></div>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary login-submit" disabled={busy}>{busy ? 'Iniciando sesión…' : 'Iniciar sesión'} <Icon name="arrow" size={18} /></button><button type="button" className="secondary-button login-demo-submit" onClick={demoLogin} disabled={busy}>Entrar a la demo</button><div className="demo-note"><Icon name="shield" size={17} /><span>Entorno de demostración · Autenticación mock<br />Usa un correo válido y cualquier contraseña de 4 caracteres. No uses credenciales reales.</span></div></form></section></main>; }
