import { Link, useParams, useSearchParams } from "react-router-dom";
import { BusinessHeader } from "../components/layout/BusinessHeader";

const termsSections = [
  { id: "objeto", title: "1. Objeto y aceptación", paragraphs: ["Estos Términos y condiciones regulan el acceso y uso de WIT Negocios, una herramienta para que las personas administren la presencia digital de uno o varios negocios en WIT.", "Al crear una cuenta, iniciar sesión o utilizar cualquier función de WIT Negocios, aceptas estos términos y la Política de privacidad. Si no estás de acuerdo, debes abstenerte de usar la plataforma."] },
  { id: "servicio", title: "2. Alcance del servicio", paragraphs: ["WIT Negocios permite crear y administrar perfiles de negocio, información de contacto, productos, servicios, imágenes, horarios y otros contenidos destinados a ser mostrados en el ecosistema WIT.", "La plataforma puede incorporar, modificar, suspender o retirar funciones. Algunas herramientas pueden estar en desarrollo o requerir conexión posterior con servicios de autenticación, pagos o terceros."] },
  { id: "cuenta", title: "3. Cuenta y seguridad", paragraphs: ["Debes proporcionar información verdadera, completa y actualizada. Eres responsable de mantener la confidencialidad de tus credenciales y de toda actividad realizada desde tu cuenta.", "No puedes compartir, vender, ceder ni transferir tu cuenta sin autorización. Debes avisarnos tan pronto detectes un acceso no autorizado, uso fraudulento o cualquier incidente de seguridad.", "Una persona puede administrar más de un negocio, pero solo debe publicar información sobre negocios que esté autorizada a representar."] },
  { id: "contenido", title: "4. Contenido y obligaciones del negocio", paragraphs: ["Conservas los derechos sobre el contenido que cargas. Al publicarlo, otorgas a WIT una licencia no exclusiva, mundial, gratuita y limitada al funcionamiento, promoción y mejora de la plataforma, incluyendo su reproducción, adaptación técnica, almacenamiento y comunicación dentro de WIT.", "Garantizas que tienes los permisos necesarios sobre nombres, marcas, fotografías, textos, precios y demás materiales que publiques, y que su uso no infringe derechos de terceros."], bullets: ["La información debe ser exacta, verificable y no engañosa.", "No publiques contenido ilegal, discriminatorio, difamatorio, amenazante, sexualmente explícito o que promueva violencia.", "No uses WIT para suplantar personas o negocios, distribuir malware, hacer spam, extraer datos o intentar vulnerar la plataforma.", "No publiques datos personales de terceros sin autorización o una base legal válida."] },
  { id: "opiniones", title: "5. Opiniones, reportes y moderación", paragraphs: ["Las opiniones y valoraciones pertenecen a quienes las publican. WIT no garantiza que cada opinión sea exacta y no responde por las declaraciones de terceros.", "Podemos revisar, ocultar, limitar o retirar contenido y cuentas cuando exista una infracción de estos términos, una orden de autoridad, un riesgo para la comunidad o señales de fraude. Procuraremos aplicar criterios razonables y permitir que presentes una explicación cuando corresponda."] },
  { id: "relacion", title: "6. Relación con consumidores y terceros", paragraphs: ["WIT es una plataforma de información y gestión de presencia digital. Salvo que se indique expresamente lo contrario, no somos el vendedor, proveedor, fabricante, empleador, agente ni representante de los negocios publicados.", "Cada negocio responde directamente por sus productos, servicios, precios, disponibilidad, publicidad, permisos, entregas, garantías, reclamos y obligaciones frente a consumidores y autoridades. Cualquier compra o acuerdo se celebra entre el negocio y su cliente."] },
  { id: "propiedad", title: "7. Propiedad intelectual", paragraphs: ["La marca WIT, su diseño, software, textos, interfaces, bases de datos y demás elementos de la plataforma pertenecen a WIT o se utilizan bajo licencia. Estos términos no transfieren ningún derecho de propiedad intelectual.", "Solo puedes usar la plataforma para sus fines permitidos y no puedes copiarla, descompilarla, realizar ingeniería inversa, crear servicios derivados o utilizar sus signos distintivos sin autorización escrita."] },
  { id: "disponibilidad", title: "8. Disponibilidad y responsabilidad", paragraphs: ["Trabajamos para mantener WIT disponible y segura, pero no garantizamos que opere sin interrupciones, errores o pérdidas de información. Podemos realizar mantenimientos, cambios o suspensiones temporales.", "En la medida permitida por la ley, WIT no responde por decisiones tomadas con base en información publicada por terceros, interrupciones de servicios externos, pérdida de oportunidades comerciales, lucro cesante ni daños indirectos.", "Nada de estos términos limita derechos irrenunciables del consumidor ni excluye responsabilidades que la ley no permita excluir."] },
  { id: "suspension", title: "9. Suspensión y terminación", paragraphs: ["Puedes dejar de usar WIT Negocios y solicitar el cierre de tu cuenta mediante los canales disponibles. Podemos suspender o cerrar cuentas, retirar contenido o limitar funciones si incumples estos términos, generas riesgos, actúas de forma fraudulenta o cuando sea necesario para proteger la plataforma y a sus usuarios.", "Las obligaciones que por su naturaleza deban continuar —incluidas propiedad intelectual, responsabilidad, datos y solución de controversias— seguirán vigentes después del cierre."] },
  { id: "datos", title: "10. Datos personales", paragraphs: ["El tratamiento de datos personales se realiza conforme a la Política de privacidad y a la normativa aplicable, incluyendo la Ley 1581 de 2012 y sus normas reglamentarias en Colombia. La Política de privacidad explica las finalidades, derechos y canales para ejercerlos."] },
  { id: "cambios", title: "11. Cambios y ley aplicable", paragraphs: ["Podemos actualizar estos términos para reflejar cambios legales, técnicos o funcionales. Publicaremos la versión vigente en esta página e indicaremos su fecha de actualización. Si el cambio es relevante, solicitaremos una nueva aceptación cuando corresponda.", "Estos términos se interpretan de acuerdo con las leyes de la República de Colombia. Las controversias se someterán a las autoridades competentes, sin perjuicio de los derechos que la ley reconozca a consumidores y titulares de datos."] },
];

export function LegalPage() {
  const { page = "terms" } = useParams();
  const [searchParams] = useSearchParams();
  const origin = searchParams.get("from") === "ajustes" ? "ajustes" : "registro";
  const backPath = origin === "ajustes" ? "/configuracion" : "/registro";
  const legalPath = (document: string) => `/legal/${document}?from=${origin}`;
  const isTerms = page === "terms";
  return <main className="legal-page">
    <BusinessHeader />
    <div className="legal-layout">
      <aside className="legal-sidebar"><span className="page-eyebrow">CENTRO LEGAL</span><h1>{isTerms ? "Términos y condiciones" : "Política de privacidad"}</h1><p>Información clara para usar WIT Negocios con confianza.</p><nav aria-label="Documentos legales"><Link className={isTerms ? "active" : ""} to={legalPath("terms")}>Términos y condiciones</Link><Link className={!isTerms ? "active" : ""} to={legalPath("privacy")}>Política de privacidad</Link></nav></aside>
      <article className="legal-card legal-document"><div className="legal-document-heading"><span className="page-eyebrow">WIT NEGOCIOS · DOCUMENTO LEGAL</span><h2>{isTerms ? "Términos y condiciones" : "Política de privacidad"}</h2><p>Última actualización: 3 de octubre de 2026</p></div>
        {isTerms ? <><nav className="legal-toc" aria-label="Contenido del documento"><strong>En este documento</strong>{termsSections.map(section => <a key={section.id} href={`#${section.id}`}>{section.title}</a>)}</nav>{termsSections.map(section => <section className="legal-section" id={section.id} key={section.id}><h3>{section.title}</h3>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}</> : <><section className="legal-section"><h3>Tratamiento de datos</h3><p>Esta política explicará las finalidades, derechos y canales aplicables al tratamiento de datos personales en WIT. Su contenido debe completarse antes de activar el registro definitivo.</p></section><section className="legal-section"><h3>Marco aplicable</h3><p>El tratamiento se organizará conforme a la Ley 1581 de 2012, sus normas reglamentarias y las instrucciones de la autoridad colombiana competente.</p></section></>}
        <Link className="text-link legal-back" to={backPath}>← Volver a {origin}</Link>
      </article>
    </div>
  </main>;
}
