import { Link } from "react-router-dom";
import { PageHeader } from "../components/common/PageHeader";
import { useBusinessStore } from "../services/businessStore";
import type { Preferences } from "../types/business";

export function SettingsPage() {
  const { account, preferences, setPreferences } = useBusinessStore();
  const toggle = (key: keyof Preferences) => setPreferences({ ...preferences, [key]: !preferences[key] });
  return <><PageHeader eyebrow="TU ESPACIO" title="Configuración" description="Administra tus preferencias, privacidad y acceso a la cuenta." /><div className="settings-layout"><div className="content-stack"><section className="surface-card"><div className="card-heading"><div><h2>Cuenta</h2><p>Datos de la persona que administra este negocio.</p></div><Link className="text-link" to="/perfil">Editar perfil →</Link></div><div className="account-summary"><span className="account-avatar">{account.name.split(" ").map(part => part[0]).slice(0,2).join("")}</span><div><strong>{account.name}</strong><span>{account.email}</span><small>{account.role}</small></div></div></section><section className="surface-card"><div className="card-heading"><div><h2>Notificaciones</h2><p>Elige los avisos que te gustaría recibir cuando se active el servicio.</p></div></div><div className="preference-list"><Preference title="Resumen por correo" detail="Actividad y novedades de tu negocio" checked={preferences.emailUpdates} onChange={() => toggle("emailUpdates")} /><Preference title="Nuevas opiniones" detail="Aviso cuando alguien publique una opinión" checked={preferences.reviewAlerts} onChange={() => toggle("reviewAlerts")} /><Preference title="Interés en productos y servicios" detail="Aviso sobre elementos que reciben más atención" checked={preferences.interestAlerts} onChange={() => toggle("interestAlerts")} /></div></section><section className="surface-card"><div className="card-heading"><div><h2>Privacidad</h2><p>Controla la visibilidad de tu información comercial.</p></div></div><div className="preference-list"><Preference title="Perfil visible en WIT" detail="Visibilidad de tu información comercial" checked={preferences.profileVisible} onChange={() => toggle("profileVisible")} /></div><div className="settings-legal-links"><Link className="text-link" to="/legal/terms?from=ajustes">Términos y condiciones →</Link><Link className="text-link" to="/legal/privacy?from=ajustes">Política de privacidad →</Link></div></section></div><aside className="content-stack"><section className="surface-card side-panel"><span className="panel-icon blue">⌑</span><h2>Seguridad</h2><p>El cambio de contraseña y la autenticación estarán disponibles con el backend.</p><Link className="outline-button inline-button" to="/login">Ver pantalla de acceso</Link></section></aside></div></>;
}

function Preference({ title, detail, checked, onChange }: { title: string; detail: string; checked: boolean; onChange: () => void }) {
  return <label className="preference-row"><span><strong>{title}</strong><small>{detail}</small></span><input type="checkbox" checked={checked} onChange={onChange} /><span className="switch-track" aria-hidden="true" /></label>;
}
