import { useState } from "react";
import { Link } from "react-router-dom";
import { PageHeader } from "../components/common/PageHeader";
import { businessCatalog } from "../data/business.mock";
import { useBusinessStore } from "../services/businessStore";

const periods = ["7 días", "30 días", "90 días"] as const;
const data = {
  "7 días": { views: 312, calls: 11, whatsapp: 19, directions: 7, bars: [28,36,43,38,55,72,66] },
  "30 días": { views: 1284, calls: 42, whatsapp: 83, directions: 23, bars: [25,33,41,38,52,47,61,58,68,62,74,82] },
  "90 días": { views: 3690, calls: 126, whatsapp: 231, directions: 69, bars: [22,31,29,44,38,53,48,62,58,64,76,84] },
};
const businessStats: Record<string, typeof data> = {
  "La Arepería de Majo": data,
  "Droguería San Jorge": { "7 días": { views: 246, calls: 18, whatsapp: 31, directions: 12, bars: [24,32,44,49,53,63,71] }, "30 días": { views: 1038, calls: 76, whatsapp: 122, directions: 45, bars: [28,37,42,48,55,61,67,63,72,69,78,86] }, "90 días": { views: 2980, calls: 214, whatsapp: 356, directions: 138, bars: [24,35,31,46,43,55,51,66,62,70,79,88] } },
  "Casa del Tornillo": { "7 días": { views: 184, calls: 9, whatsapp: 14, directions: 11, bars: [22,29,38,35,48,58,64] }, "30 días": { views: 742, calls: 38, whatsapp: 61, directions: 47, bars: [22,31,39,36,48,45,57,54,63,59,68,77] }, "90 días": { views: 2160, calls: 108, whatsapp: 175, directions: 132, bars: [20,28,27,40,36,49,45,58,54,61,72,81] } },
};
const emptyData: typeof data = { "7 días": { views: 0, calls: 0, whatsapp: 0, directions: 0, bars: [0,0,0,0,0,0,0] }, "30 días": { views: 0, calls: 0, whatsapp: 0, directions: 0, bars: [0,0,0,0,0,0,0,0,0,0,0,0] }, "90 días": { views: 0, calls: 0, whatsapp: 0, directions: 0, bars: [0,0,0,0,0,0,0,0,0,0,0,0] } };

export function StatisticsPage() {
  const { items: storedItems, business, businesses } = useBusinessStore();
  const personalCatalog = businesses.length === 0 || business.isNew || !businessCatalog[business.name];
  const items = business.catalog ?? (personalCatalog ? storedItems : (businessCatalog[business.name] ?? storedItems));
  const [period, setPeriod] = useState<typeof periods[number]>("30 días");
  const hasEmptyData = businesses.length === 0 || business.isNew || (!businessStats[business.name] && !businessCatalog[business.name]);
  const current = (hasEmptyData ? emptyData : (businessStats[business.name] ?? data))[period];
  const products = items.filter(item => item.kind === "product");
  const services = items.filter(item => item.kind === "service");
  const leaders = [...items].filter(item => item.active).sort((a, b) => b.interest - a.interest).slice(0, 4);
  const totalLikes = items.reduce((sum, item) => sum + (item.active ? item.interest : 0), 0);
  const totalContacts = current.whatsapp + current.calls + current.directions;
  const contactRate = current.views ? Math.round((totalContacts / current.views) * 100) : 0;
  const rating = hasEmptyData ? 0 : (business.rating ?? 4.8);
  const reviews = hasEmptyData ? 0 : (business.reviewCount ?? 24);
  const activeItems = items.filter(item => item.active).length;
  const periodLabel = period === "7 días" ? "esta semana" : period === "30 días" ? "este mes" : "estos 90 días";
  const businessIndex = Math.max(0, businesses.indexOf(business));
  const metrics = [["Visualizaciones", current.views, "◉", "Personas que vieron tu negocio"], ["WhatsApp", current.whatsapp, "◌", "Clics para contactarte"], ["Llamadas", current.calls, "☎", "Clics en tu teléfono"], ["Cómo llegar", current.directions, "⌖", "Solicitudes de ubicación"]] as const;
  const profileScore = hasEmptyData ? 0 : Math.min(100, Math.round(([business.name, business.category, business.description, business.city, business.address, business.phone, business.hours, business.coverImage || business.images?.length].filter(Boolean).length / 8) * 100));
  return <>
    <PageHeader eyebrow="RENDIMIENTO" title="Estadísticas" description={businesses.length === 0 ? "Aquí aparecerán tus cifras cuando crees tu primera tienda." : `Una mirada sencilla al rendimiento de ${business.name}.`} action={<div className="period-tabs" role="group" aria-label="Periodo de estadísticas">{periods.map(value => <button type="button" className={period === value ? "selected" : ""} aria-pressed={period === value} onClick={() => setPeriod(value)} key={value}>{value}</button>)}</div>} />
    <section className="stats-overview" aria-label="Resumen de rendimiento">{metrics.map(([label, value, icon, detail]) => <article className="surface-card stat-tile" key={label}><span className="stat-icon">{icon}</span><p>{label}</p><strong>{Number(value).toLocaleString("es-CO")}</strong><small>{detail} · {period}</small></article>)}<article className="surface-card stat-tile stat-tile-accent"><span className="stat-icon">↗</span><p>Tasa de contacto</p><strong>{contactRate}%</strong><small>Visitas que generaron una acción</small></article></section>
    <div className="statistics-main-grid">
      <section className="surface-card chart-card"><div className="card-heading"><div><h2>Visibilidad de tu negocio</h2><p>Visualizaciones de tu ficha durante los últimos {period}</p></div><span className="chart-legend"><i /> Visualizaciones</span></div><div className="bar-chart" role="img" aria-label={`Gráfico de visualizaciones en los últimos ${period}`}><div className="chart-grid"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="chart-bars">{current.bars.map((value, index) => <div className="chart-column" key={index}><span style={{ height: `${value}%` }} /><small>{period === "7 días" ? ["L", "M", "M", "J", "V", "S", "D"][index] : index % 2 === 0 ? `${index + 1}` : ""}</small></div>)}</div></div></section>
      <section className="surface-card stats-contact-card"><div className="card-heading"><div><h2>Acciones de contacto</h2><p>Qué hicieron las personas después de visitarte</p></div></div><div className="contact-stat-row"><span className="contact-stat-icon whatsapp">◌</span><div><strong>WhatsApp</strong><small>Contactos generados</small></div><b>{current.whatsapp}</b></div><div className="contact-stat-row"><span className="contact-stat-icon phone">☎</span><div><strong>Llamadas</strong><small>Intentos de contacto</small></div><b>{current.calls}</b></div><div className="contact-stat-row"><span className="contact-stat-icon map">⌖</span><div><strong>Cómo llegar</strong><small>Interés en visitar</small></div><b>{current.directions}</b></div></section>
    </div>
    <div className="statistics-bottom-grid">
      <section className="surface-card top-interest"><div className="card-heading"><div><h2>Lo que más gusta</h2><p>Productos y servicios con más interacciones</p></div></div>{leaders.length ? leaders.map((item, index) => <div className="leader-row" key={item.id}><span className="leader-index">0{index + 1}</span><span className="leader-icon">{item.image}</span><div><strong>{item.name}</strong><small>{item.kind === "product" ? "Producto" : "Servicio"}</small></div><b>👍 {item.interest}</b></div>) : <div className="stats-empty-copy"><span>◇</span><p>Aún no tienes productos o servicios activos.</p></div>}</section>
      <section className="surface-card stats-inventory-card"><div className="card-heading"><div><h2>Tu oferta</h2><p>Elementos activos que las personas pueden ver</p></div></div><div className="offer-stat"><span>Productos activos</span><strong>{products.filter(item => item.active).length}</strong></div><div className="offer-stat"><span>Servicios activos</span><strong>{services.filter(item => item.active).length}</strong></div><div className="offer-stat"><span>Me gusta acumulados</span><strong>{totalLikes}</strong></div></section>
      <section className="surface-card stats-profile-card"><div className="card-heading"><div><h2>Perfil del negocio</h2><p>Información disponible para las personas</p></div><strong className="profile-score">{profileScore}%</strong></div><div className="profile-progress"><span style={{ width: `${profileScore}%` }} /></div><p className="profile-message">{profileScore >= 100 ? "Tu información está completa." : profileScore === 0 ? "Crea y completa tu negocio para comenzar." : "Completa los datos pendientes para mejorar tu presencia."}</p></section>
    </div>
    <div className="statistics-insights-grid">
      <section className="surface-card stats-performance-card"><div className="card-heading"><div><h2>Rendimiento de tu oferta</h2><p>Cómo se distribuye el interés de las personas</p></div></div><div className="performance-bars"><div><div className="performance-label"><span>Productos</span><b>{products.filter(item => item.active).length} activos</b></div><div className="performance-track"><span style={{width:`${activeItems ? Math.round((products.filter(item => item.active).length / activeItems) * 100) : 0}%`}} /></div></div><div><div className="performance-label"><span>Servicios</span><b>{services.filter(item => item.active).length} activos</b></div><div className="performance-track services"><span style={{width:`${activeItems ? Math.round((services.filter(item => item.active).length / activeItems) * 100) : 0}%`}} /></div></div></div><div className="performance-summary"><strong>{totalLikes.toLocaleString("es-CO")}</strong><span>me gusta acumulados en tu oferta</span></div></section>
      <section className="surface-card stats-reputation-card"><div className="card-heading"><div><h2>Reputación</h2><p>La percepción de tus clientes</p></div></div><div className="reputation-score"><strong>{rating ? rating.toFixed(1) : "0.0"}</strong><span>★</span><small>{reviews} opiniones</small></div><div className="rating-distribution"><div><span>5 ★</span><i><b style={{width: hasEmptyData ? "0%" : "82%"}} /></i><em>{hasEmptyData ? 0 : 82}%</em></div><div><span>4 ★</span><i><b style={{width: hasEmptyData ? "0%" : "13%"}} /></i><em>{hasEmptyData ? 0 : 13}%</em></div><div><span>3 ★ o menos</span><i><b style={{width: hasEmptyData ? "0%" : "5%"}} /></i><em>{hasEmptyData ? 0 : 5}%</em></div></div></section>
      <section className="surface-card stats-activity-card"><div className="card-heading"><div><h2>Momentos de mayor interés</h2><p>Cuándo suelen buscarte</p></div></div><div className="activity-row"><span>☀️</span><div><strong>Mediodía</strong><small>11:00 a. m. – 2:00 p. m.</small></div><b>{hasEmptyData ? 0 : 46}%</b></div><div className="activity-row"><span>🌙</span><div><strong>Final de la tarde</strong><small>5:00 p. m. – 8:00 p. m.</small></div><b>{hasEmptyData ? 0 : 31}%</b></div><p className="stats-insight">{hasEmptyData ? "Cuando recibas visitas aparecerán aquí tus mejores horarios." : `Tu mayor actividad se concentra ${periodLabel}.`}</p></section>
    </div>
    <section className="surface-card stats-recommendations"><div className="card-heading"><div><h2>Recomendaciones para crecer</h2><p>Acciones sencillas basadas en el comportamiento de tu negocio</p></div></div><div className="recommendation-list"><div><span className="recommendation-icon">＋</span><p><strong>Agrega más contenido visual</strong><small>Las fotos ayudan a que las personas conozcan mejor tu oferta.</small></p><Link className="recommendation-link" to={`/mis-negocios/editar/${businessIndex}`}>Editar negocio →</Link></div><div><span className="recommendation-icon green">↗</span><p><strong>Activa todos tus productos y servicios</strong><small>Una oferta completa aumenta las oportunidades de contacto.</small></p><Link className="recommendation-link" to="/productos">Ver productos →</Link></div><div><span className="recommendation-icon gold">★</span><p><strong>Invita a tus clientes a opinar</strong><small>Las opiniones recientes fortalecen la confianza en tu negocio.</small></p><Link className="recommendation-link" to="/opiniones">Ver opiniones →</Link></div></div></section>
  </>;
}
